version: '3'
services:
  node:
    build: ./docker/node
    container_name: 'node'
    tty: true
    volumes:
      - ./:/root/src
    working_dir: "/root/src/src"
    depends_on:
      - db
    links:
      - db
  db:                           # DBサーバ用コンテナ
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./src/logs:/var/log/mysql
      - ./docker/mysql/db:/root
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=vl_develop
      - MYSQL_USER=vladmin
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - TZ=Asia/Tokyo

volumes:
  db-store: